const products = {
    'fructe-legume': [
        { id: 1, name: 'Măr', price: 3 },
        { id: 2, name: 'Banana', price: 4 },
        { id: 3, name: 'Căpșuni', price: 6 },
        { id: 4, name: 'Portocală', price: 5 },
        { id: 5, name: 'Lămâie', price: 2 },
        { id: 6, name: 'Kiwi', price: 7 },
        { id: 7, name: 'Mango', price: 9 },
        { id: 8, name: 'Ananas', price: 12 },
        { id: 9, name: 'Struguri', price: 4 },
        { id: 10, name: 'Pere', price: 5 },
        { id: 11, name: 'Pepene verde', price: 8 },
        { id: 12, name: 'Pepene galben', price: 8 }
    ],
    'tigari': [
        { id: 13, name: 'Marlboro', price: 15 },
        { id: 14, name: 'Parliament', price: 16 },
        { id: 15, name: 'Winston', price: 14 },
        { id: 16, name: 'Camel', price: 13 },
        { id: 17, name: 'Chesterfield', price: 12 },
        { id: 18, name: 'Kent', price: 17 },
        { id: 19, name: 'L&M', price: 11 },
        { id: 20, name: 'Lucky Strike', price: 18 },
        { id: 21, name: 'Pall Mall', price: 14 },
        { id: 22, name: 'Viceroy', price: 13 },
        { id: 23, name: 'West', price: 12 }
    ],
    'produse-curatenie': [
        { id: 24, name: 'Detergent de Rufe', price: 20 },
        { id: 25, name: 'Detergent de Vase', price: 10 },
        { id: 26, name: 'Curățitor de Suprafață', price: 15 },
        { id: 27, name: 'Curățitor de Geamuri', price: 12 },
        { id: 28, name: 'Curățitor de Toaletă', price: 8 },
        { id: 29, name: 'Curățitor de Baie', price: 11 },
        { id: 30, name: 'Înălbitor', price: 7 },
        { id: 31, name: 'Curățitor de Lemn', price: 14 },
        { id: 32, name: 'Decalcifiant', price: 9 },
        { id: 33, name: 'Curățitor de Bucătărie', price: 10 },
        { id: 34, name: 'Șampon de Covor', price: 18 },
        { id: 35, name: 'Detergent pentru Pete', price: 12 }
    ],
    'produse-carne': [
        { id: 36, name: 'Carne Tocată', price: 50 },
        { id: 37, name: 'Filet', price: 70 },
        { id: 38, name: 'Friptură', price: 65 },
        { id: 39, name: 'Cotlet de Miel', price: 80 },
        { id: 40, name: 'Rost de Vită', price: 75 },
        { id: 41, name: 'Piept de Pui', price: 30 },
        { id: 42, name: 'Aripi de Pui', price: 28 },
        { id: 43, name: 'Ciocănele de Pui', price: 32 },
        { id: 44, name: 'Cârnați', price: 45 },
        { id: 45, name: 'Cremwurști', price: 20 },
        { id: 46, name: 'Jambon', price: 35 },
        { id: 47, name: 'Pastirma', price: 90 },
        { id: 48, name: 'Salam', price: 25 }
    ],
    'gustari': [
        { id: 49, name: 'Chipsuri', price: 5 },
        { id: 50, name: 'Ciocolată', price: 7 },
        { id: 51, name: 'Napolitane', price: 3 },
        { id: 52, name: 'Crocanți', price: 4 },
        { id: 53, name: 'Crackers', price: 6 },
        { id: 54, name: 'Nuci', price: 15 },
        { id: 55, name: 'Floricele', price: 2 },
        { id: 56, name: 'Gumă de Mestecat', price: 1 },
        { id: 57, name: 'Bomboane', price: 5 },
        { id: 58, name: 'Biscuiți', price: 4 },
        { id: 59, name: 'Baton de Fructe', price: 8 },
        { id: 60, name: 'Baton Energetic', price: 10 }
    ],
    'produse-brutarie': [
        { id: 61, name: 'Pâine', price: 2 },
        { id: 62, name: 'Pogăci', price: 3 },
        { id: 63, name: 'Covrig', price: 2 },
        { id: 64, name: 'Prăjitură', price: 5 },
        { id: 65, name: 'Fursecuri', price: 4 },
        { id: 66, name: 'Plăcintă', price: 6 },
        { id: 67, name: 'Tort', price: 20 },
        { id: 68, name: 'Sandviș', price: 8 },
        { id: 69, name: 'Pide', price: 12 },
        { id: 70, name: 'Lavaș', price: 4 },
        { id: 71, name: 'Gogoașă', price: 5 },
        { id: 72, name: 'Tartă', price: 7 }
    ],
    'bauturi': [
        { id: 73, name: 'Cola', price: 4 },
        { id: 74, name: 'Suc de Fructe', price: 5 },
        { id: 75, name: 'Apă', price: 1 },
        { id: 76, name: 'Băutură Gazoasă', price: 3 },
        { id: 77, name: 'Băutură Energetică', price: 8 },
        { id: 78, name: 'Ceai', price: 10 },
        { id: 79, name: 'Cafea', price: 15 },
        { id: 80, name: 'Apă Minerală', price: 2 },
        { id: 81, name: 'Ayran', price: 3 },
        { id: 82, name: 'Milkshake', price: 6 },
        { id: 83, name: 'Smoothie', price: 7 },
        { id: 84, name: 'Șalgam', price: 4 }
    ],
    'produse-machiaj': [
        { id: 85, name: 'Ruj', price: 20 },
        { id: 86, name: 'Fond de ten', price: 30 },
        { id: 87, name: 'Blush', price: 25 },
        { id: 88, name: 'Paletă de Farduri', price: 35 },
        { id: 89, name: 'Eyeliner', price: 15 },
        { id: 90, name: 'Mascara', price: 18 },
        { id: 91, name: 'Creion pentru Sprâncene', price: 12 },
        { id: 92, name: 'Iluminator', price: 28 },
        { id: 93, name: 'Paletă Contur', price: 30 },
        { id: 94, name: 'BB Cream', price: 22 },
        { id: 95, name: 'CC Cream', price: 25 },
        { id: 96, name: 'Primer pentru Machiaj', price: 27 },
        { id: 97, name: 'Demachiant', price: 19 }
    ],
    'inghetate': [
        { id: 98, name: 'Înghețată de Vanilie', price: 10 },
        { id: 99, name: 'Înghețată de Ciocolată', price: 12 },
        { id: 100, name: 'Înghețată de Fructe', price: 11 },
        { id: 101, name: 'Înghețată Maraș', price: 15 },
        { id: 102, name: 'Sundae', price: 14 },
        { id: 103, name: 'Înghețată la Cornet', price: 8 },
        { id: 104, name: 'Tort de Înghețată', price: 20 },
        { id: 105, name: 'Parfait', price: 18 },
        { id: 106, name: 'Sorbet', price: 12 },
        { id: 107, name: 'Sandviș cu Înghețată', price: 16 },
        { id: 108, name: 'Înghețată pe Băț', price: 7 },
        { id: 109, name: 'Magnum', price: 10 }
    ],
    'produse-bebelusi': [
        { id: 110, name: 'Scutece pentru Bebeluși', price: 40 },
        { id: 111, name: 'Piure pentru Bebeluși', price: 25 },
        { id: 112, name: 'Șervețele Umde', price: 5 },
        { id: 113, name: 'Șampon pentru Bebeluși', price: 15 },
        { id: 114, name: 'Loțiune pentru Bebeluși', price: 20 },
        { id: 115, name: 'Ulei pentru Bebeluși', price: 18 },
        { id: 116, name: 'Pudră pentru Bebeluși', price: 10 },
        { id: 117, name: 'Biberon', price: 12 },
        { id: 118, name: 'Suzetă', price: 8 },
        { id: 119, name: 'Păturică pentru Bebeluși', price: 30 },
        { id: 120, name: 'Lenjerie pentru Bebeluși', price: 25 },
        { id: 121, name: 'Jucării pentru Bebeluși', price: 35 }
    ],
    'alimente-uscate': [
        { id: 122, name: 'Paste', price: 5 },
        { id: 123, name: 'Orez', price: 8 },
        { id: 124, name: 'Bulgur', price: 6 },
        { id: 125, name: 'Năut', price: 10 },
        { id: 126, name: 'Linte', price: 9 },
        { id: 127, name: 'Fasole', price: 7 },
        { id: 128, name: 'Cuscus', price: 8 },
        { id: 129, name: 'Quinoa', price: 15 },
        { id: 130, name: 'Supa', price: 5 },
        { id: 131, name: 'Tarhana', price: 12 },
        { id: 132, name: 'Fidea', price: 4 },
        { id: 133, name: 'Griș', price: 6 }
    ],
    'conserve': [
        { id: 134, name: 'Ton la Conservă', price: 15 },
        { id: 135, name: 'Conservă de Mazăre', price: 10 },
        { id: 136, name: 'Conservă de Porumb', price: 8 },
        { id: 137, name: 'Conservă de Fasole', price: 9 },
        { id: 138, name: 'Conservă de Roșii', price: 7 },
        { id: 139, name: 'Conservă de Ardei', price: 8 },
        { id: 140, name: 'Conservă de Anghinare', price: 14 },
        { id: 141, name: 'Conservă de Fasole Verde', price: 12 },
        { id: 142, name: 'Conservă de Morcovi', price: 9 },
        { id: 143, name: 'Conservă de Ciuperci', price: 10 },
        { id: 144, name: 'Murături de Castraveți', price: 7 },
        { id: 145, name: 'Murături de Ardei Roșii', price: 8 }
    ],
    'produse-lactate': [
        { id: 146, name: 'Lapte', price: 4 },
        { id: 147, name: 'Iaurt', price: 6 },
        { id: 148, name: 'Brânză', price: 12 },
        { id: 149, name: 'Unt', price: 15 },
        { id: 150, name: 'Chefir', price: 8 },
        { id: 151, name: 'Ayran', price: 3 },
        { id: 152, name: 'Smântână', price: 18 },
        { id: 153, name: 'Frișcă', price: 10 },
        { id: 154, name: 'Lapte praf', price: 14 },
        { id: 155, name: 'Labne', price: 9 },
        { id: 156, name: 'Cașcaval', price: 20 },
        { id: 157, name: 'Brânză de Vaci', price: 11 },
        { id: 158, name: 'Brânză Telemea', price: 13 }
    ],
    'produse-mic-dejun': [
        { id: 159, name: 'Măsline', price: 10 },
        { id: 160, name: 'Brânză', price: 12 },
        { id: 161, name: 'Miere', price: 20 },
        { id: 162, name: 'Gem', price: 15 },
        { id: 163, name: 'Unt', price: 18 },
        { id: 164, name: 'Ouă', price: 7 },
        { id: 165, name: 'Covrig', price: 2 },
        { id: 166, name: 'Smântână', price: 25 },
        { id: 167, name: 'Cârnați', price: 22 },
        { id: 168, name: 'Melasă', price: 12 },
        { id: 169, name: 'Tahini', price: 15 },
        { id: 170, name: 'Brânză Cremă', price: 8 }
    ],
    'produse-animale': [
        { id: 171, name: 'Hrană pentru Pisici', price: 20 },
        { id: 172, name: 'Hrană pentru Câini', price: 30 },
        { id: 173, name: 'Nisip pentru Pisici', price: 15 },
        { id: 174, name: 'Lesă pentru Câini', price: 25 },
        { id: 175, name: 'Jucărie pentru Pisici', price: 12 },
        { id: 176, name: 'Jucărie pentru Câini', price: 18 },
        { id: 177, name: 'Hrană pentru Păsări', price: 10 },
        { id: 178, name: 'Hrană pentru Pești', price: 8 },
        { id: 179, name: 'Scratcher pentru Pisici', price: 40 },
        { id: 180, name: 'Căsuță pentru Câini', price: 60 },
        { id: 181, name: 'Pat pentru Pisici', price: 35 },
        { id: 182, name: 'Șampon pentru Câini', price: 20 }
    ],
    'produse-ingrijire-personala': [
        { id: 183, name: 'Șampon', price: 15 },
        { id: 184, name: 'Pastă de Dinți', price: 10 },
        { id: 185, name: 'Săpun', price: 5 },
        { id: 186, name: 'Deodorant', price: 12 },
        { id: 187, name: 'Spumă de Ras', price: 14 },
        { id: 188, name: 'Aparat de Ras', price: 20 },
        { id: 189, name: 'Cremă pentru Față', price: 25 },
        { id: 190, name: 'Cremă pentru Mâini', price: 10 },
        { id: 191, name: 'Loțiune pentru Corp', price: 18 },
        { id: 192, name: 'Apă de Gură', price: 12 },
        { id: 193, name: 'Spray pentru Păr', price: 15 },
        { id: 194, name: 'Curățător pentru Față', price: 20 },
        { id: 195, name: 'Cremă pentru Ochi', price: 22 }
    ],
    'alimente-congelate': [
        { id: 196, name: 'Pizza Congelată', price: 20 },
        { id: 197, name: 'Legume Congelate', price: 12 },
        { id: 198, name: 'Fructe Congelate', price: 10 },
        { id: 199, name: 'Pui Congelat', price: 25 },
        { id: 200, name: 'Pește Congelat', price: 30 },
        { id: 201, name: 'Cartofi Congelați', price: 8 },
        { id: 202, name: 'Plăcintă Congelată', price: 15 },
        { id: 203, name: 'Mantı Congelat', price: 18 },
        { id: 204, name: 'Chiftele Congelate', price: 22 },
        { id: 205, name: 'Hamburger Congelat', price: 20 },
        { id: 206, name: 'Deserturi Congelate', price: 15 },
        { id: 207, name: 'Mâncăruri Congelate', price: 25 }
    ],
    'suplimente-alimentare': [
        { id: 208, name: 'Vitamina C', price: 25 },
        { id: 209, name: 'Ulei de Pește', price: 35 },
        { id: 210, name: 'Multivitamine', price: 40 },
        { id: 211, name: 'Pudră de Proteine', price: 50 },
        { id: 212, name: 'Creatină', price: 45 },
        { id: 213, name: 'Aminoacizi', price: 30 },
        { id: 214, name: 'Calciu', price: 20 },
        { id: 215, name: 'Magneziu', price: 22 },
        { id: 216, name: 'Vitamina D', price: 25 },
        { id: 217, name: 'Vitamina E', price: 28 },
        { id: 218, name: 'Vitamina B Complex', price: 32 },
        { id: 219, name: 'Glucozamină', price: 35 }
    ],
    'produse-electronice': [
        { id: 220, name: 'Baterii', price: 10 },
        { id: 221, name: 'Căști', price: 50 },
        { id: 222, name: 'Încărcător', price: 20 },
        { id: 223, name: 'Cablu USB', price: 15 },
        { id: 224, name: 'Powerbank', price: 60 },
        { id: 225, name: 'Boxă Bluetooth', price: 80 },
        { id: 226, name: 'Husă pentru Telefon', price: 25 },
        { id: 227, name: 'Protecție de Ecran', price: 10 },
        { id: 228, name: 'Geantă pentru Laptop', price: 100 },
        { id: 229, name: 'Mouse', price: 30 },
        { id: 230, name: 'Tastatură', price: 40 },
        { id: 231, name: 'Webcam', price: 70 }
    ],
    'produse-casnice': [
        { id: 232, name: 'Sac de Gunoi', price: 5 },
        { id: 233, name: 'Burete', price: 3 },
        { id: 234, name: 'Mănuși de Vase', price: 4 },
        { id: 235, name: 'Pânză de Podea', price: 6 },
        { id: 236, name: 'Pânză din Microfibră', price: 8 },
        { id: 237, name: 'Găleată de Curățenie', price: 15 },
        { id: 238, name: 'Masă de Călcat', price: 50 },
        { id: 239, name: 'Coș de Rufe', price: 30 },
        { id: 240, name: 'Suport de Uscat Haine', price: 20 },
        { id: 241, name: 'Mop', price: 25 },
        { id: 242, name: 'Aspirator', price: 60 },
        { id: 243, name: 'Sac de Aspirator', price: 12 }
    ]
};
